spellchecker: aspell
matrix:
pipeline:
    - pyspelling.filters.markdown:
        markdown_extensions:
        - pymdownx.superfences
    - pyspelling.filters.html:
        comments: false
        ignores:
        - code
        - pre
        - init
- name: Text Files
  sources:
  - "**/*.txt"
  - "**/*.md"